### ISSUE TITLE
LT vers. <3.3 not available

### ISSUE THREAD

**Issue by nmueller18** [fiduswriter/fiduswriter-languagetool#5]
Unfortunately, following the instructions in the Readme throws an error because LT vers. <3.3 are no longer available via pip. We have tried to use a newer version and change the line `LT_URL = 'http://localhost:8081'` to `LT_URL = 'http://localhost:8081/v2'` but to no avail. Any suggestions what to do else would be much appreciated.

**Comment by johanneswilm** [comment]
Hey @nmueller18 ,
the instructions said that for Fidus Writer 3.2 you need to install the plugin < 3.3 (meaning: the last 3.2.x version). The point was simply that the plugin major/minor versions need to match that of the installed version of Fidus Writer. I have now updated the instructions to make it even clearer how to ensure that the plugin works with the main fidus writer version.

You don't need to worry about "v2" or anything else like that. And you can install any of the latest ten or so languagetool versions. It should work with all of them, but of course you may just as well install the latest version.

**Comment by nmueller18** [comment]
Thanks for the clarification!
