### ISSUE TITLE
Unhandled rejection with LT

### ISSUE THREAD

**Issue by nmueller18** [fiduswriter/fiduswriter-languagetool#6]
With FW and LT both vers. 3.10. on our server, I receive the following error message (in Safari, Firefox and Chrome, Mac OS 10.13.6) when invoking the Spell/grammar checker:
`unhandledrejection, JSON.parse: unexpected character at line 1 column 1 of the JSON data`
Safari for exemple reports: `Failed to load resource: the server responded with a status of 500 (Internal Server Error)`
I suspect that our webserver settings have to be amended but any suggestions where to start are appreciated.

**Comment by johanneswilm** [comment]
It looks like it doesn't get a connection with the LT server. Have you checked that it is working?

Btw - all these issues would be non-issues if you used the Snap instead + you would always get all updates installed automatically.

**Comment by nmueller18** [comment]
It dawns on me that you need to set up a LT server separately. Is this correct?

**Comment by johanneswilm** [comment]
Yes! It can be on the same computer though. Languagetool is a Java program, so it requires a java executable, etc..

**Comment by nmueller18** [comment]
💡. Maybe add a sentence to the Readme like "A working LT server is a prerequiste"?

**Comment by johanneswilm** [comment]
@nmueller18 done!
